#!/bin/sh

DAEMON="aesdsocket"

case "${1}" in
	start)
		printf "Starting %s\n" "${DAEMON}"
		start-stop-daemon -Sqx "/usr/bin/${DAEMON}" -- -d
		;;
	stop)
		printf "Stopping %s\n" "${DAEMON}"
		start-stop-daemon -Kqx "/usr/bin/${DAEMON}"
		;;
	*)
		printf "Usage: %s {start|stop}\n" "${0}"
		exit 1;
esac

exit 0
